/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteDAO;
import model.Cliente;

import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Elivelton
 */
public class ViewConsultaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaCliente
     */
    private JDesktopPane jDesktopPane2;

    public ViewConsultaCliente(JDesktopPane jdp) {
        initComponents();
        jDesktopPane2 = jdp;
        DefaultTableModel dtmCLiente = (DefaultTableModel) tabCliente.getModel();
        tabCliente.setRowSorter(new TableRowSorter(dtmCLiente));
        this.limpar();
        leituraTabela();

    }

    public void leituraTabela() {

        DefaultTableModel dtmCliente = (DefaultTableModel) tabCliente.getModel();
        dtmCliente.setNumRows(0);
        ClienteDAO objCdao = new ClienteDAO();

        for (Cliente cli : objCdao.Leitura()) {

            dtmCliente.addRow(new Object[]{
                cli.getIdCliente(),
                cli.getNomeCliente(),
                cli.getCpfCliente(),
                cli.getEndCliente(),
                cli.getBaiCliente(),
                cli.getCidCliente(),
                cli.getUfCliente(),
                cli.getCepCliente(),
                cli.getTelCliente(),
                cli.getEmCliente(),});

        }

    }

    public void leituraTabPesquisar(String nomeCliente) {

        DefaultTableModel dtmCliente = (DefaultTableModel) tabCliente.getModel();
        dtmCliente.setNumRows(0);
        ClienteDAO objCdao = new ClienteDAO();

        for (Cliente cli : objCdao.Pesquisar(nomeCliente)) {

            dtmCliente.addRow(new Object[]{
                cli.getIdCliente(),
                cli.getNomeCliente(),
                cli.getCpfCliente(),
                cli.getEndCliente(),
                cli.getBaiCliente(),
                cli.getCidCliente(),
                cli.getUfCliente(),
                cli.getCepCliente(),
                cli.getTelCliente(),
                cli.getEmCliente(),});

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabCliente = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JButton();
        txtExcluir = new javax.swing.JButton();
        txtAlterar = new javax.swing.JButton();
        txtNovo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtEnd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBai = new javax.swing.JTextField();
        txtNomeCli = new javax.swing.JTextField();
        txtCid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUF = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtEm = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        txtTele = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Cliente");
        setPreferredSize(new java.awt.Dimension(630, 430));
        setRequestFocusEnabled(false);

        tabCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "CPF", "Endereço", "Bairro", "Cidade", "UF", "CEP", "Telefone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabClienteMouseClicked(evt);
            }
        });
        tabCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabClienteKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabCliente);

        txtPesquisar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/zoom.png"))); // NOI18N
        txtPesquisar.setText("Pesquisar");
        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });

        txtExcluir.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_delete.png"))); // NOI18N
        txtExcluir.setText("Excluir");
        txtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExcluirActionPerformed(evt);
            }
        });

        txtAlterar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_edit.png"))); // NOI18N
        txtAlterar.setText("Alterar");
        txtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlterarActionPerformed(evt);
            }
        });

        txtNovo.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_add.png"))); // NOI18N
        txtNovo.setText("Novo");
        txtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNovoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel10.setText("CEP");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setText("Nome");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setText("CPF");

        txtUF.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RS", "RR", "RO", "SP", "SC", "SE", "TO" }));
        txtUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUFActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setText("Endereço");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel6.setText("Bairro");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel7.setText("Cidade");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel8.setText("UF");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel9.setText("Telefone");

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel11.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(txtExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNovo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(txtNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(txtTele, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEm, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(txtUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBai, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCid, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPesquisar)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExcluir)
                    .addComponent(txtAlterar)
                    .addComponent(txtNovo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNovoActionPerformed
        // TODO add your handling code here:

        ViewCadastrarCliente objCadastrarCliente = new ViewCadastrarCliente();
        jDesktopPane2.add(objCadastrarCliente);
        objCadastrarCliente.setVisible(true);
        leituraTabela();
    }//GEN-LAST:event_txtNovoActionPerformed

    private void txtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExcluirActionPerformed
        // TODO add your handling code here:

        if (tabCliente.getSelectedRow() != -1) {

            Cliente objcliente = new Cliente();
            ClienteDAO dao = new ClienteDAO();

            objcliente.setIdCliente((int) tabCliente.getValueAt(tabCliente.getSelectedRow(), 0));
            dao.Excluir(objcliente);

            txtNomeCli.setText("");
            txtCpf.setText("");
            txtEnd.setText("");
            txtBai.setText("");
            txtCid.setText("");
            txtCep.setText("");
            txtTele.setText("");
            txtEm.setText("");

            leituraTabela();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente para excluir!");
        }

    }//GEN-LAST:event_txtExcluirActionPerformed

    private void txtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlterarActionPerformed
        // TODO add your handling code here

        if (tabCliente.getSelectedRow() != -1) {

            Cliente objcliente = new Cliente();
            ClienteDAO dao = new ClienteDAO();
            objcliente.setNomeCliente(txtNomeCli.getText());
            objcliente.setCpfCliente(txtCpf.getText());
            objcliente.setCpfCliente(txtCpf.getText());
            objcliente.setEndCliente(txtEnd.getText());
            objcliente.setBaiCliente(txtBai.getText());
            objcliente.setCidCliente(txtCid.getText());
            objcliente.setUfCliente(txtUF.getSelectedItem().toString());
            objcliente.setCepCliente(txtCep.getText());
            objcliente.setTelCliente(txtTele.getText());
            objcliente.setEmCliente(txtEm.getText());
            objcliente.setIdCliente((int) tabCliente.getValueAt(tabCliente.getSelectedRow(), 0));
            dao.Alterar(objcliente);

            txtNomeCli.setText("");
            txtCpf.setText("");
            txtEnd.setText("");
            txtBai.setText("");
            txtCid.setText("");
            txtUF.setSelectedItem("");
            txtCep.setText("");
            txtTele.setText("");
            txtEm.setText("");

            leituraTabela();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione cliente para atualizar");
        }


    }//GEN-LAST:event_txtAlterarActionPerformed

    private void tabClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabClienteKeyReleased
        // TODO add your handling code here:

        if (tabCliente.getSelectedRow() != -1) {

            txtNomeCli.setText(tabCliente.getValueAt(tabCliente.getSelectedRow(), 1).toString());
            txtCpf.setText(tabCliente.getValueAt(tabCliente.getSelectedRow(), 2).toString());
            txtEnd.setText(tabCliente.getValueAt(tabCliente.getSelectedRow(), 3).toString());
            txtBai.setText(tabCliente.getValueAt(tabCliente.getSelectedRow(), 4).toString());
            txtCid.setText(tabCliente.getValueAt(tabCliente.getSelectedRow(), 5).toString());
            txtCep.setText(tabCliente.getValueAt(tabCliente.getSelectedRow(), 7).toString());
            txtTele.setText(tabCliente.getValueAt(tabCliente.getSelectedRow(), 8).toString());
            txtEm.setText(tabCliente.getValueAt(tabCliente.getSelectedRow(), 9).toString());

        }

    }//GEN-LAST:event_tabClienteKeyReleased

    private void txtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepActionPerformed

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        // TODO add your handling code here:

        leituraTabPesquisar(txtPesquisar.getText());


    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void txtUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUFActionPerformed

    private void tabClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabClienteMouseClicked
           // TODO add your handling code here:
           
           if(tabCliente.getSelectedRow() != -1){
               
               txtNomeCli.setText(tabCliente.getValueAt(tabCliente.getSelectedRow(), 1).toString());
               txtCpf.setText(tabCliente.getValueAt(tabCliente.getSelectedRow(), 2).toString());
               txtEnd.setText(tabCliente.getValueAt(tabCliente.getSelectedRow(), 3).toString());
               txtBai.setText(tabCliente.getValueAt(tabCliente.getSelectedRow(), 4).toString());
               txtCid.setText(tabCliente.getValueAt(tabCliente.getSelectedRow(), 5).toString());
               txtCep.setText(tabCliente.getValueAt(tabCliente.getSelectedRow(), 6).toString());
               txtTele.setText(tabCliente.getValueAt(tabCliente.getSelectedRow(), 7).toString());
               txtEm.setText(tabCliente.getValueAt(tabCliente.getSelectedRow(), 8).toString());
               
           }
           
    }//GEN-LAST:event_tabClienteMouseClicked

   
    private void limpar() {
        txtNomeCli.setText("");
        txtCpf.setText("");
        txtEnd.setText("");
        txtBai.setText("");
        txtCid.setText("");
        txtCep.setText("");
        txtTele.setText("");
        txtEm.setText("");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabCliente;
    private javax.swing.JButton txtAlterar;
    private javax.swing.JTextField txtBai;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCid;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEm;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JButton txtExcluir;
    private javax.swing.JTextField txtNomeCli;
    private javax.swing.JButton txtNovo;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JButton txtPesquisar;
    private javax.swing.JTextField txtTele;
    private javax.swing.JComboBox<String> txtUF;
    // End of variables declaration//GEN-END:variables
}
